const supportedElements = new Set([
  'Svg',
  'svg',
  'Path',
  'path',
  'Circle',
  'circle',
  'Ellipse',
  'ellipse',
  'Rect',
  'rect',
  'Line',
  'line',
  'Polyline',
  'polyline',
  'Polygon',
  'polygon',
  'Text',
  'text',
  'G',
  'g',
  'Defs',
  'defs',
  'ClipPath',
  'clipPath',
  'Mask',
  'mask',
  'LinearGradient',
  'linearGradient',
  'RadialGradient',
  'radialGradient',
  'Pattern',
  'pattern',
  'Use',
  'use',
  'Image',
  'image',
  'Stop',
  'stop',
]);

const elementNameMap = new Map<string, string>([
  ['Svg', 'svg'],
  ['svg', 'svg'],
  ['Path', 'path'],
  ['path', 'path'],
  ['Circle', 'circle'],
  ['circle', 'circle'],
  ['Ellipse', 'ellipse'],
  ['ellipse', 'ellipse'],
  ['Rect', 'rect'],
  ['rect', 'rect'],
  ['Line', 'line'],
  ['line', 'line'],
  ['Polyline', 'polyline'],
  ['polyline', 'polyline'],
  ['Polygon', 'polygon'],
  ['polygon', 'polygon'],
  ['Text', 'text'],
  ['text', 'text'],
  ['G', 'g'],
  ['g', 'g'],
  ['Defs', 'defs'],
  ['defs', 'defs'],
  ['ClipPath', 'clipPath'],
  ['clipPath', 'clipPath'],
  ['Mask', 'mask'],
  ['mask', 'mask'],
  ['LinearGradient', 'linearGradient'],
  ['linearGradient', 'linearGradient'],
  ['RadialGradient', 'radialGradient'],
  ['radialGradient', 'radialGradient'],
  ['Pattern', 'pattern'],
  ['pattern', 'pattern'],
  ['Use', 'use'],
  ['use', 'use'],
  ['Image', 'image'],
  ['image', 'image'],
  ['Stop', 'stop'],
  ['stop', 'stop'],
]);

const attributeNameMap = new Map<string, string>([
  ['strokeWidth', 'stroke-width'],
  ['strokeLinecap', 'stroke-linecap'],
  ['strokeLinejoin', 'stroke-linejoin'],
  ['strokeMiterlimit', 'stroke-miterlimit'],
  ['strokeMiterLimit', 'stroke-miterlimit'],
  ['strokeDasharray', 'stroke-dasharray'],
  ['strokeDashoffset', 'stroke-dashoffset'],
  ['strokeOpacity', 'stroke-opacity'],
  ['fillOpacity', 'fill-opacity'],
  ['fillRule', 'fill-rule'],
  ['clipRule', 'clip-rule'],
  ['clipPath', 'clip-path'],
  ['stopColor', 'stop-color'],
  ['stopOpacity', 'stop-opacity'],
  ['fontSize', 'font-size'],
  ['fontFamily', 'font-family'],
  ['fontWeight', 'font-weight'],
  ['textAnchor', 'text-anchor'],
  ['shapeRendering', 'shape-rendering'],
  ['xlinkHref', 'href'],
  ['xlink:href', 'href'],
  ['className', 'class'],
]);

export function isSupportedSvgElement(name: string): boolean {
  return supportedElements.has(name);
}

export function convertSvgElementName(name: string): string {
  return elementNameMap.get(name) ?? name;
}

export function convertSvgAttributeName(name: string): string {
  return attributeNameMap.get(name) ?? name;
}
